# Generated by Django 4.0.1 on 2022-02-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='pincode',
        ),
    ]
