# Generated by Django 4.0.1 on 2022-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_appuser_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='contact',
            field=models.CharField(default='', max_length=200),
        ),
    ]
