# Generated by Django 4.0.1 on 2022-02-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_appuser_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appuser')),
            ],
        ),
    ]
