# Generated by Django 4.0.1 on 2022-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'genre',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(to='books.Genre'),
        ),
    ]
