# Generated by Django 4.0.1 on 2022-04-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_book_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books',
            new_name='genre',
        ),
    ]
